name: dart_frog_backend_demo
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0
  dart_frog: ^1.2.6
  dart_frog_web_socket: ^1.0.3
  json_annotation: ^4.9.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.0.0
